version: '3'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fullcycle
    ports:
      - 3307:3306

# docker compose up -d
