FROM nginx:latest

COPY html/index.html /usr/share/nginx/html/index.html


# docker build -t freitasmiranda/mynginx:latest .
# docker run -d --name nginx -p 8080:80 mynginx
# docker stop nginx && docker rm nginx
# docker push freitasmiranda/mynginx:latest
