version: '3.8'

services:
  
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - my-network
    volumes:
      - mongodb_data:/data/db


  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
    networks:
      - my-network      
    volumes:
      - mongo_express_data:/data/db           
      
volumes:
  mongodb_data:
    driver: local
  mongo_express_data:
    driver: local
          
networks:
  my-network:
    external: true

# //Linux ou Mac
# /etc/hosts

# 127.0.0.1 host.docker.internal

# //Windows
# C:\Windows\system32\drivers\etc\hosts (bloco de notas como administrador)
# 127.0.0.1 host.docker.internal



# docker compose up -d --no-deps --build
# docker compose down --rmi all
# docker-compose up --force-recreate -d
