apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
      - containerPort: 80

### Criar o pod
# kubectl apply -f .\pod.yaml 

### Verificar pods rodando
# kubectl get pods

### Deletar pod pelo nome
# kubectl delete pod nginx