apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx-replicaset
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80

### Criar o ReplicaSet
# kubectl apply -f replicaset.yaml

### Listar os ReplicaSet
# kubectl get rs

### Deletar os ReplicaSet
# kubectl delete rs nginx-replicaset

### Escalar a aplicação com 3 Pods
# kubectl scale replicaset nginx-replicaset --replicas=3
