GET http://localhost:3000

###
GET http://localhost:3000/api/assets

###
POST http://localhost:3000/api/assets
Content-Type: application/json

{
  "id": "asset1",
  "symbol": "A1"
}


### 
GET http://localhost:3000/api/orders

###
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "asset_id": "asset1",
  "price": 101,
}
