version: '3'

services:
  app:
    container_name: app-nest
    build: .
    volumes:
      - .:/home/node/app
    command: >
      bash -c "npx prisma generate
      && npm run dev"
    ports:
      - 3000:3000
      - 5555:5555
    networks:
      - my-network

  mongodb:
    container_name: mongodb
    image: bitnami/mongodb:5.0.17
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: nest
    ports:
      - 27017:27017
    networks:
      - my-network

networks:
  my-network:
    external: true
